export enum Routes {
  Index = "/",
  Login = "/login",
  Register = "/register",
  Profile = "/profile",
  Posts = "/posts",
  PostsSearch = "/posts",
  PostsCreate = "/posts/create",
  PostsMap = "/posts/map",
  PostsDetails = "/posts/:id",
  NotFound = "/not-found",
  ServerError = "/server-error",
  Map = "/map",
  ConfirmEmail = "/confirm-email",
  Wildcard = "*",
}
