export enum Routes {
  Index = "/",
  Login = "/login",
  Register = "/register",
  Profile = "/profile",
  Events = "/events",
  EventsSearch = "/events",
  EventsCreate = "/events/create",
  EventsMap = "/events/map",
  EventsDetails = "/events/:id",
  NotFound = "/not-found",
  ServerError = "/server-error",
  ConfirmEmail = "/confirm-email",
  Requsts = "/requsts",
  Wildcard = "*",
}
