name: Run .NET Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/CityShare.Backend.Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Run all tests
        run: dotnet test --no-restore
